export const products = [
  {
    id: "flight-lisbon-enlightenment",
    slug: "slightly-delayed-enlightenment-flight",
    type: "flight",
    destination: "Lisbon",
    tripType: "city",
    name: "Slightly Delayed Enlightenment Flight",
    tagline: "Nonstop, except emotionally.",
    price: 320,
    margin: 0.18,
    duration: "3h 05m",
    departureDate: "2026-09-12",
    returnDate: "2026-09-18",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1400&q=80",
    tags: ["city", "business", "couples", "budget"],
    details: ["Carry-on included", "Window-seat optimism available", "Carbon offset with tasteful humility"]
  },
  {
    id: "hotel-lisbon-optimistic-view",
    slug: "hotel-room-with-optimistic-sea-view",
    type: "hotel",
    destination: "Lisbon",
    tripType: "city",
    name: "Hotel Room With Optimistic Sea View",
    tagline: "If you lean left, the Atlantic appears.",
    price: 680,
    margin: 0.32,
    duration: "6 nights",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    tags: ["city", "couples", "vip", "hotel"],
    details: ["Breakfast buffet", "Late checkout", "Desk for dramatic journaling"]
  },
  {
    id: "package-mallorca-family-patience",
    slug: "family-trip-engineered-for-snacks",
    type: "package",
    destination: "Mallorca",
    tripType: "family",
    name: "Family Trip Engineered for Snacks",
    tagline: "Naps, pools, and tactical patience.",
    price: 2450,
    margin: 0.28,
    duration: "7 nights",
    departureDate: "2026-08-08",
    returnDate: "2026-08-15",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "beach", "package", "kids"],
    details: ["Family room", "Snack-forward transfers", "Pool proximity: excellent"]
  },
  {
    id: "flight-zurich-breakfast-meeting",
    slug: "meeting-elsewhere-better-breakfast",
    type: "flight",
    destination: "Zurich",
    tripType: "business",
    name: "Meeting Elsewhere, Better Breakfast",
    tagline: "A business fare with punctual feelings.",
    price: 410,
    margin: 0.2,
    duration: "1h 25m",
    departureDate: "2026-10-03",
    returnDate: "2026-10-05",
    image: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "city", "flight", "short-haul"],
    details: ["Priority boarding", "Invoice-friendly receipt", "Early arrival smugness"]
  },
  {
    id: "hotel-zurich-executive-nap",
    slug: "executive-nap-lounge-hotel",
    type: "hotel",
    destination: "Zurich",
    tripType: "business",
    name: "Executive Nap Lounge Hotel",
    tagline: "Calendar-compatible comfort.",
    price: 890,
    margin: 0.35,
    duration: "2 nights",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "vip", "hotel"],
    details: ["Quiet floor", "Espresso density: high", "Checkout after the awkward meeting"]
  },
  {
    id: "package-kyoto-pretend-understand",
    slug: "guided-tour-places-you-pretend-to-understand",
    type: "package",
    destination: "Kyoto",
    tripType: "culture",
    name: "Guided Tour of Places You Pretend to Understand",
    tagline: "Beautiful, profound, and mostly explained.",
    price: 3180,
    margin: 0.31,
    duration: "9 nights",
    departureDate: "2026-11-02",
    returnDate: "2026-11-11",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "vip", "package", "couples"],
    details: ["Temple route", "Local guide", "Tea ceremony with gentle corrections"]
  },
  {
    id: "transfer-emotional-support",
    slug: "airport-transfer-of-emotional-support",
    type: "transfer",
    destination: "Lisbon",
    tripType: "city",
    name: "Airport Transfer of Emotional Support",
    tagline: "Someone holding a sign solves more than you think.",
    price: 58,
    margin: 0.44,
    duration: "35 min",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1400&q=80",
    tags: ["transfer", "family", "business", "add-on"],
    details: ["Meet and greet", "Flight tracking", "Zero taxi-line philosophy"]
  },
  {
    id: "addon-lounge-nap",
    slug: "executive-nap-lounge-access",
    type: "add_on",
    destination: "Zurich",
    tripType: "business",
    name: "Executive Nap Lounge Access",
    tagline: "A chair that understands quarterly pressure.",
    price: 74,
    margin: 0.62,
    duration: "3 hours",
    image: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "vip", "flight", "add-on"],
    details: ["Fast Wi-Fi", "Quiet pods", "Tiny sandwiches with confidence"]
  },
  {
    id: "addon-baggage-metaphorical",
    slug: "baggage-insurance-against-metaphorical-loss",
    type: "insurance",
    destination: "Mallorca",
    tripType: "family",
    name: "Baggage Insurance Against Metaphorical Loss",
    tagline: "Covers suitcases. The rest is a journey.",
    price: 39,
    margin: 0.67,
    duration: "Trip coverage",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
    tags: ["insurance", "family", "package", "add-on"],
    details: ["Lost baggage", "Delay cover", "One small existential clause"]
  },
  {
    id: "exp-sunset-networking",
    slug: "sunset-cruise-with-mild-networking-risk",
    type: "experience",
    destination: "Lisbon",
    tripType: "leisure",
    name: "Sunset Cruise With Mild Networking Risk",
    tagline: "Golden hour, tasteful small talk.",
    price: 96,
    margin: 0.5,
    duration: "2h 30m",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
    tags: ["experience", "couples", "city", "add-on"],
    details: ["River cruise", "Welcome drink", "Conversation escape routes"]
  },
  {
    id: "exp-pretend-understand",
    slug: "places-you-pretend-to-understand-afternoon",
    type: "experience",
    destination: "Kyoto",
    tripType: "culture",
    name: "Afternoon of Places You Pretend to Understand",
    tagline: "A compact cultural confidence booster.",
    price: 118,
    margin: 0.55,
    duration: "4 hours",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1400&q=80",
    tags: ["experience", "culture", "vip", "add-on"],
    details: ["Local expert", "Quiet streets", "Polite nodding encouraged"]
  },
  {
    id: "package-iceland-configurable-expectations",
    slug: "romantic-weekend-configurable-expectations",
    type: "package",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Romantic Weekend With Configurable Expectations",
    tagline: "Hot springs, cool boundaries.",
    price: 1980,
    margin: 0.29,
    duration: "4 nights",
    departureDate: "2026-12-04",
    returnDate: "2026-12-08",
    image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "couples", "package", "vip"],
    details: ["Spa entry", "Northern lights chase", "One expectation alignment dinner"]
  }
];

export const featuredDestinationIds = [
  "flight-lisbon-enlightenment",
  "package-mallorca-family-patience",
  "package-kyoto-pretend-understand",
  "package-iceland-configurable-expectations"
];
