export const products = [
  {
    id: "flight-lisbon-enlightenment",
    slug: "slightly-delayed-enlightenment-flight",
    type: "flight",
    destination: "Lisbon",
    tripType: "city",
    name: "Slightly Delayed Enlightenment Flight",
    tagline: "Nonstop, except emotionally.",
    price: 320,
    margin: 0.18,
    duration: "3h 05m",
    departureDate: "2026-09-12",
    returnDate: "2026-09-18",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1400&q=80",
    tags: ["city", "business", "couples", "budget"],
    details: ["Carry-on included", "Window-seat optimism available", "Carbon offset with tasteful humility"]
  },
  {
    id: "hotel-lisbon-optimistic-view",
    slug: "hotel-room-with-optimistic-sea-view",
    type: "hotel",
    destination: "Lisbon",
    tripType: "city",
    name: "Hotel Room With Optimistic Sea View",
    tagline: "If you lean left, the Atlantic appears.",
    price: 680,
    margin: 0.32,
    duration: "6 nights",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    tags: ["city", "couples", "vip", "hotel"],
    details: ["Breakfast buffet", "Late checkout", "Desk for dramatic journaling"]
  },
  {
    id: "package-mallorca-family-patience",
    slug: "family-trip-engineered-for-snacks",
    type: "package",
    destination: "Mallorca",
    tripType: "family",
    name: "Family Trip Engineered for Snacks",
    tagline: "Naps, pools, and tactical patience.",
    price: 2450,
    margin: 0.28,
    duration: "7 nights",
    departureDate: "2026-08-08",
    returnDate: "2026-08-15",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "beach", "package", "kids"],
    details: ["Family room", "Snack-forward transfers", "Pool proximity: excellent"]
  },
  {
    id: "flight-zurich-breakfast-meeting",
    slug: "meeting-elsewhere-better-breakfast",
    type: "flight",
    destination: "Zurich",
    tripType: "business",
    name: "Meeting Elsewhere, Better Breakfast",
    tagline: "A business fare with punctual feelings.",
    price: 410,
    margin: 0.2,
    duration: "1h 25m",
    departureDate: "2026-10-03",
    returnDate: "2026-10-05",
    image: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "city", "flight", "short-haul"],
    details: ["Priority boarding", "Invoice-friendly receipt", "Early arrival smugness"]
  },
  {
    id: "hotel-zurich-executive-nap",
    slug: "executive-nap-lounge-hotel",
    type: "hotel",
    destination: "Zurich",
    tripType: "business",
    name: "Executive Nap Lounge Hotel",
    tagline: "Calendar-compatible comfort.",
    price: 890,
    margin: 0.35,
    duration: "2 nights",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "vip", "hotel"],
    details: ["Quiet floor", "Espresso density: high", "Checkout after the awkward meeting"]
  },
  {
    id: "package-kyoto-pretend-understand",
    slug: "guided-tour-places-you-pretend-to-understand",
    type: "package",
    destination: "Kyoto",
    tripType: "culture",
    name: "Guided Tour of Places You Pretend to Understand",
    tagline: "Beautiful, profound, and mostly explained.",
    price: 3180,
    margin: 0.31,
    duration: "9 nights",
    departureDate: "2026-11-02",
    returnDate: "2026-11-11",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "vip", "package", "couples"],
    details: ["Temple route", "Local guide", "Tea ceremony with gentle corrections"]
  },
  {
    id: "transfer-emotional-support",
    slug: "airport-transfer-of-emotional-support",
    type: "transfer",
    destination: "Lisbon",
    tripType: "city",
    name: "Airport Transfer of Emotional Support",
    tagline: "Someone holding a sign solves more than you think.",
    price: 58,
    margin: 0.44,
    duration: "35 min",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1400&q=80",
    tags: ["transfer", "family", "business", "add-on"],
    details: ["Meet and greet", "Flight tracking", "Zero taxi-line philosophy"]
  },
  {
    id: "addon-lounge-nap",
    slug: "executive-nap-lounge-access",
    type: "add_on",
    destination: "Zurich",
    tripType: "business",
    name: "Executive Nap Lounge Access",
    tagline: "A chair that understands quarterly pressure.",
    price: 74,
    margin: 0.62,
    duration: "3 hours",
    image: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "vip", "flight", "add-on"],
    details: ["Fast Wi-Fi", "Quiet pods", "Tiny sandwiches with confidence"]
  },
  {
    id: "addon-baggage-metaphorical",
    slug: "baggage-insurance-against-metaphorical-loss",
    type: "insurance",
    destination: "Mallorca",
    tripType: "family",
    name: "Baggage Insurance Against Metaphorical Loss",
    tagline: "Covers suitcases. The rest is a journey.",
    price: 39,
    margin: 0.67,
    duration: "Trip coverage",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
    tags: ["insurance", "family", "package", "add-on"],
    details: ["Lost baggage", "Delay cover", "One small existential clause"]
  },
  {
    id: "exp-sunset-networking",
    slug: "sunset-cruise-with-mild-networking-risk",
    type: "experience",
    destination: "Lisbon",
    tripType: "leisure",
    name: "Sunset Cruise With Mild Networking Risk",
    tagline: "Golden hour, tasteful small talk.",
    price: 96,
    margin: 0.5,
    duration: "2h 30m",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
    tags: ["experience", "couples", "city", "add-on"],
    details: ["River cruise", "Welcome drink", "Conversation escape routes"]
  },
  {
    id: "exp-pretend-understand",
    slug: "places-you-pretend-to-understand-afternoon",
    type: "experience",
    destination: "Kyoto",
    tripType: "culture",
    name: "Afternoon of Places You Pretend to Understand",
    tagline: "A compact cultural confidence booster.",
    price: 118,
    margin: 0.55,
    duration: "4 hours",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1400&q=80",
    tags: ["experience", "culture", "vip", "add-on"],
    details: ["Local expert", "Quiet streets", "Polite nodding encouraged"]
  },
  {
    id: "package-iceland-configurable-expectations",
    slug: "romantic-weekend-configurable-expectations",
    type: "package",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Romantic Weekend With Configurable Expectations",
    tagline: "Hot springs, cool boundaries.",
    price: 1980,
    margin: 0.29,
    duration: "4 nights",
    departureDate: "2026-12-04",
    returnDate: "2026-12-08",
    image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "couples", "package", "vip"],
    details: ["Spa entry", "Northern lights chase", "One expectation alignment dinner"]
  },
  {
    id: "flight-mallorca-snack-window",
    slug: "mallorca-flight-with-snack-window-diplomacy",
    type: "flight",
    destination: "Mallorca",
    tripType: "family",
    name: "Mallorca Flight With Snack-Window Diplomacy",
    tagline: "Boarding order optimized for tiny negotiators.",
    price: 260,
    margin: 0.19,
    duration: "2h 35m",
    departureDate: "2026-08-08",
    returnDate: "2026-08-15",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "beach", "kids", "flight", "budget"],
    details: ["Family boarding", "Seat selection included", "Snack timing advice from people with experience"]
  },
  {
    id: "hotel-mallorca-pool-proximity",
    slug: "pool-proximity-hotel-with-early-breakfast",
    type: "hotel",
    destination: "Mallorca",
    tripType: "family",
    name: "Pool-Proximity Hotel With Early Breakfast",
    tagline: "Close enough to the pool to hear joy, far enough to nap.",
    price: 1120,
    margin: 0.34,
    duration: "7 nights",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "kids", "beach", "hotel", "package"],
    details: ["Kids club", "Early breakfast", "Two-room family suite"]
  },
  {
    id: "transfer-mallorca-stroller-tetris",
    slug: "mallorca-transfer-with-stroller-tetris",
    type: "transfer",
    destination: "Mallorca",
    tripType: "family",
    name: "Mallorca Transfer With Stroller Tetris",
    tagline: "A driver who has seen every suitcase shape.",
    price: 72,
    margin: 0.48,
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "kids", "transfer", "add-on"],
    details: ["Child seats", "Flight tracking", "Room for heroic amounts of luggage"]
  },
  {
    id: "exp-mallorca-ice-cream-fieldwork",
    slug: "mallorca-ice-cream-fieldwork-expedition",
    type: "experience",
    destination: "Mallorca",
    tripType: "family",
    name: "Ice Cream Fieldwork Expedition",
    tagline: "A rigorous tasting route with beach-adjacent conclusions.",
    price: 84,
    margin: 0.52,
    duration: "3 hours",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
    tags: ["family", "kids", "experience", "beach", "add-on"],
    details: ["Three tasting stops", "Short walking route", "Emergency nap window preserved"]
  },
  {
    id: "flight-kyoto-quiet-anticipation",
    slug: "kyoto-flight-with-quiet-anticipation",
    type: "flight",
    destination: "Kyoto",
    tripType: "culture",
    name: "Kyoto Flight With Quiet Anticipation",
    tagline: "Long-haul calm for people practicing thoughtful nodding.",
    price: 860,
    margin: 0.21,
    duration: "14h 10m",
    departureDate: "2026-11-02",
    returnDate: "2026-11-11",
    image: "https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "vip", "flight", "couples"],
    details: ["One-stop route", "Meal preference support", "Jet lag sympathy included"]
  },
  {
    id: "hotel-kyoto-paper-door-poise",
    slug: "kyoto-ryokan-with-paper-door-poise",
    type: "hotel",
    destination: "Kyoto",
    tripType: "culture",
    name: "Ryokan With Paper-Door Poise",
    tagline: "Traditional calm, modern Wi-Fi, no sudden furniture.",
    price: 1540,
    margin: 0.38,
    duration: "5 nights",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "vip", "hotel", "couples"],
    details: ["Tatami room", "Private bath", "Breakfast that deserves attention"]
  },
  {
    id: "transfer-kyoto-politeness-buffer",
    slug: "kyoto-station-transfer-politeness-buffer",
    type: "transfer",
    destination: "Kyoto",
    tripType: "culture",
    name: "Station Transfer With Politeness Buffer",
    tagline: "From platform confusion to quiet arrival.",
    price: 64,
    margin: 0.46,
    duration: "30 min",
    image: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "transfer", "vip", "add-on"],
    details: ["Station meet-up", "Luggage assistance", "Hotel check-in timing"]
  },
  {
    id: "addon-kyoto-tea-confidence",
    slug: "kyoto-tea-ceremony-confidence-upgrade",
    type: "add_on",
    destination: "Kyoto",
    tripType: "culture",
    name: "Tea Ceremony Confidence Upgrade",
    tagline: "For guests who want to look serene on purpose.",
    price: 52,
    margin: 0.61,
    duration: "90 min",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1400&q=80",
    tags: ["culture", "experience", "vip", "add-on"],
    details: ["Small group", "Etiquette intro", "Gentle correction policy"]
  },
  {
    id: "flight-reykjavik-weather-theatre",
    slug: "reykjavik-flight-to-weather-theatre",
    type: "flight",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Reykjavik Flight to Weather Theatre",
    tagline: "Arrive prepared for drama in three layers.",
    price: 390,
    margin: 0.2,
    duration: "4h 05m",
    departureDate: "2026-12-04",
    returnDate: "2026-12-08",
    image: "https://images.unsplash.com/photo-1474302770737-173ee21bab63?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "couples", "flight", "budget"],
    details: ["Carry-on included", "Northern route", "Weather flexibility suggestions"]
  },
  {
    id: "hotel-reykjavik-thermal-robe",
    slug: "reykjavik-hotel-with-thermal-robe-energy",
    type: "hotel",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Hotel With Thermal Robe Energy",
    tagline: "A lobby designed for post-lag decompression.",
    price: 940,
    margin: 0.36,
    duration: "4 nights",
    image: "https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "hotel", "vip", "couples"],
    details: ["Spa access", "Harbor walks nearby", "Breakfast with sturdy optimism"]
  },
  {
    id: "transfer-reykjavik-geothermal",
    slug: "geothermal-detour-airport-transfer",
    type: "transfer",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Geothermal Detour Airport Transfer",
    tagline: "Because going straight to the hotel lacks imagination.",
    price: 118,
    margin: 0.49,
    duration: "2 hours",
    image: "https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "transfer", "add-on", "couples"],
    details: ["Lagoon stop", "Towel included", "Hotel drop-off after visible relaxation"]
  },
  {
    id: "exp-reykjavik-lights-maybe",
    slug: "northern-lights-maybe-with-hot-chocolate",
    type: "experience",
    destination: "Reykjavik",
    tripType: "wellness",
    name: "Northern Lights Maybe, With Hot Chocolate",
    tagline: "Aurora probability managed with warm beverages.",
    price: 142,
    margin: 0.57,
    duration: "4 hours",
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1400&q=80",
    tags: ["wellness", "experience", "couples", "vip", "add-on"],
    details: ["Weather monitoring", "Photo guidance", "Backup storytelling if clouds attend"]
  },
  {
    id: "package-lisbon-remote-work-escape",
    slug: "lisbon-remote-work-escape-with-real-sunlight",
    type: "package",
    destination: "Lisbon",
    tripType: "business",
    name: "Remote-Work Escape With Real Sunlight",
    tagline: "Standups in the morning, pastries during moral recovery.",
    price: 1460,
    margin: 0.3,
    duration: "5 nights",
    departureDate: "2026-09-22",
    returnDate: "2026-09-27",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "city", "package", "vip"],
    details: ["Hotel workspace", "Fast Wi-Fi", "Late checkout after final call"]
  },
  {
    id: "hotel-lisbon-tile-and-deadline",
    slug: "lisbon-hotel-for-tiles-and-deadlines",
    type: "hotel",
    destination: "Lisbon",
    tripType: "business",
    name: "Hotel for Tiles and Deadlines",
    tagline: "Pretty walls, practical desk, acceptable espresso density.",
    price: 760,
    margin: 0.33,
    duration: "4 nights",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "city", "hotel", "vip"],
    details: ["Desk setup", "Quiet room", "Invoice-ready checkout"]
  },
  {
    id: "addon-lisbon-pastry-priority",
    slug: "lisbon-pastry-priority-pass",
    type: "add_on",
    destination: "Lisbon",
    tripType: "city",
    name: "Pastry Priority Pass",
    tagline: "Skip the uncertainty. Meet the custard.",
    price: 34,
    margin: 0.66,
    duration: "2 hours",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1400&q=80",
    tags: ["city", "experience", "add-on", "couples", "budget"],
    details: ["Two pastry stops", "Coffee pairing", "No spreadsheet required"]
  },
  {
    id: "package-zurich-boardroom-decompression",
    slug: "zurich-boardroom-decompression-package",
    type: "package",
    destination: "Zurich",
    tripType: "business",
    name: "Boardroom Decompression Package",
    tagline: "Meetings, mountains, and a controlled amount of silence.",
    price: 1720,
    margin: 0.32,
    duration: "3 nights",
    departureDate: "2026-10-03",
    returnDate: "2026-10-06",
    image: "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "vip", "package", "city"],
    details: ["Business hotel", "Airport transfer", "Half-day mountain reset"]
  },
  {
    id: "transfer-zurich-slide-deck",
    slug: "zurich-transfer-with-slide-deck-recovery",
    type: "transfer",
    destination: "Zurich",
    tripType: "business",
    name: "Transfer With Slide Deck Recovery",
    tagline: "Quiet car, charging cable, no questions about Q4.",
    price: 88,
    margin: 0.47,
    duration: "25 min",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "transfer", "vip", "add-on"],
    details: ["Premium sedan", "Phone charger", "Invoice-friendly receipt"]
  },
  {
    id: "insurance-calendar-chaos",
    slug: "calendar-chaos-flex-insurance",
    type: "insurance",
    destination: "Zurich",
    tripType: "business",
    name: "Calendar Chaos Flex Insurance",
    tagline: "For trips rescheduled by people who write 'quick sync'.",
    price: 64,
    margin: 0.69,
    duration: "Trip coverage",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=80",
    tags: ["business", "insurance", "add-on", "vip"],
    details: ["Change protection", "Cancellation support", "Meeting-moved-again tolerance"]
  }
];

export const featuredDestinationIds = [
  "flight-lisbon-enlightenment",
  "package-mallorca-family-patience",
  "package-kyoto-pretend-understand",
  "package-iceland-configurable-expectations"
];
